In [1]:
import numpy as np
from math import atan2,sin,cos,asin
import math

In [2]:
class Homogeneous_conversion():
    def __init__(self):
        self.T0 = np.matrix([[1,0,0,0],
                            [0,1,0,0],
                            [0,0,1,0],
                            [0,0,0,1]])

    ### 回転行列 ###
    def rotation_matrix(self,th):
        rad = np.radians(th)
        rad_x = rad[0]
        rad_y = rad[1]
        rad_z = rad[2]

        Rx = np.matrix([[1.,0.,0.,0.],
                       [0.,cos(rad_x),-sin(rad_x),0.],
                       [0.,sin(rad_x),cos(rad_x),0.],
                       [0.,0.,0.,1.]])

        Ry = np.matrix([[cos(rad_y),0.,sin(rad_y),0.],
                       [0.,1.,0.,0.],
                       [-sin(rad_y),0.,cos(rad_y),0.],
                       [0.,0.,0.,1.]])

        Rz = np.matrix([[cos(rad_z),-sin(rad_z),0.,0.],
                       [sin(rad_z),cos(rad_z),0.,0.],
                       [0.,0.,1.,0.],
                       [0.,0.,0.,1.]])
        R = Rz * Ry * Rx
        return R

    ### 並進ベクトル ###
    def translational_vector(self,p):
        x = p[0]
        y = p[1]
        z = p[2]
        P = np.matrix([[1.,0.,0.,x],
                       [0.,1.,0.,y],
                       [0.,0.,1.,z],
                       [0.,0.,0.,1.]])
        return P

    ### 同次変換行列の計算 ###
    def calculation(self,T,p,th):
        R = self.rotation_matrix(th)
        P = self.translational_vector(p)
        T = T * P * R
        return T

In [3]:
def deg(R):
    return([atan2(round(R[2,1],10),round(R[2,2],10)),
            atan2(round(math.sqrt(math.pow(R[0,2],2) + math.pow(R[1,2],2)),10),round(R[2,2],10)),
            atan2(round(R[1,0],10),round(R[0,0],10))])

In [4]:
HC = Homogeneous_conversion()
p = [2,4,6]
th = [0,0,0]
T = HC.calculation(HC.T0,p,th)
print(T)
print(deg(T))

[[ 1.  0.  0.  2.]
 [ 0.  1.  0.  4.]
 [ 0.  0.  1.  6.]
 [ 0.  0.  0.  1.]]
[0.0, 0.0, 0.0]


In [5]:
p = [2,4,6]
th = [0,0,0]
T = HC.calculation(T,p,th)
print(T)
print(deg(T))

[[  1.   0.   0.   4.]
 [  0.   1.   0.   8.]
 [  0.   0.   1.  12.]
 [  0.   0.   0.   1.]]
[0.0, 0.0, 0.0]


In [6]:
p = [0,0,0]
th = [0,60,0]
T = HC.calculation(T,p,th)
print(T)
print(np.degrees(deg(T)))

[[  0.5         0.          0.8660254   4.       ]
 [  0.          1.          0.          8.       ]
 [ -0.8660254   0.          0.5        12.       ]
 [  0.          0.          0.          1.       ]]
[  0.  60.   0.]


In [7]:
p = [0,0,0]
th = [0,-30,0]
T = HC.calculation(T,p,th)
print(T)
print(np.degrees(deg(T)))

[[  0.8660254   0.          0.5         4.       ]
 [  0.          1.          0.          8.       ]
 [ -0.5         0.          0.8660254  12.       ]
 [  0.          0.          0.          1.       ]]
[  0.  30.   0.]


In [8]:
p = [0,0,0]
th = [0,45,0]
T = HC.calculation(T,p,th)
print(T)
print(np.degrees(deg(T)))

[[  0.25881905   0.           0.96592583   4.        ]
 [  0.           1.           0.           8.        ]
 [ -0.96592583   0.           0.25881905  12.        ]
 [  0.           0.           0.           1.        ]]
[  0.  75.   0.]


In [9]:
p = [0,0,0]
th = [0,0,50]
T = HC.calculation(T,p,th)
print(T)
print(np.degrees(deg(T)))

[[  0.16636568  -0.19826689   0.96592583   4.        ]
 [  0.76604444   0.64278761   0.           8.        ]
 [ -0.62088515   0.73994211   0.25881905  12.        ]
 [  0.           0.           0.           1.        ]]
[ 70.72103959  75.          77.74706277]
