In [55]:
import numpy as np
from math import sin,cos,atan2,asin
import math

In [66]:
def R(th_x,th_y,th_z):
    
    th_x = np.radians(th_x)
    th_y = np.radians(th_y)
    th_z = np.radians(th_z)
    
    Rx = np.array([
        [1.,0.,0.],
        [0.,cos(th_x),-sin(th_x)],
        [0.,sin(th_x),cos(th_x)]
    ])
    Ry = np.array([
        [cos(th_y),0.,sin(th_y)],
        [0.,1.,0.],
        [-sin(th_y),0.,cos(th_y)]
    ])
    Rz = np.array([
        [cos(th_z),-sin(th_z),0.],
        [sin(th_z),cos(th_z),0.],
        [0.,0.,1.]
    ])
    
    Ra = Rz @ Ry @ Rx
    
    return Ra

In [92]:
def deg(R):
    r = atan2(R[2,1], R[2,2])
    p = asin(-R[2,0])
    y = atan2(R[1,0],R[0,0])
    print(r, p, y)
    return np.rad2deg(r), np.degrees(p), np.degrees(y)
    #return([atan2(round(R[2,1],10),round(R[2,2],10)),
            #atan2(round(math.sqrt(math.pow(R[0,2],2) + math.pow(R[1,2],2)),10),round(R[2,2],10)),
            #atan2(round(R[1,0],10),round(R[0,0],10))])

In [93]:
R0 = R(0,0,0)
print(R0)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [94]:
R1 = R(30,0,0)
print(R1)
print(deg(R1))

[[ 1.         0.         0.       ]
 [ 0.         0.8660254 -0.5      ]
 [ 0.         0.5        0.8660254]]
sin -0.0
0.5235987755982988 -0.0 0.0
(29.999999999999996, -0.0, 0.0)


In [95]:
R2 = R(30,0,0)
tmp = R1@R2
print(R1@R2)
print(deg(tmp))

[[ 1.         0.         0.       ]
 [ 0.         0.5       -0.8660254]
 [ 0.         0.8660254  0.5      ]]
sin -0.0
1.0471975511965976 -0.0 0.0
(59.999999999999993, -0.0, 0.0)


In [96]:
R3 = R(30,0,0)
tmp = R1@R2@R3
print(tmp)
print((deg(tmp)))
print("-"*20)
print(tmp@np.array([[1,0,0]]).T)
print("-"*20)
print(tmp@np.array([[0,1,0]]).T)
print("-"*20)
print(tmp@np.array([[0,0,1]]).T)
print("-"*20)

[[  1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   2.14607521e-16  -1.00000000e+00]
 [  0.00000000e+00   1.00000000e+00   2.07170437e-16]]
sin -0.0
1.5707963267948963 -0.0 0.0
(89.999999999999986, -0.0, 0.0)
--------------------
[[ 1.]
 [ 0.]
 [ 0.]]
--------------------
[[  0.00000000e+00]
 [  2.14607521e-16]
 [  1.00000000e+00]]
--------------------
[[  0.00000000e+00]
 [ -1.00000000e+00]
 [  2.07170437e-16]]
--------------------


In [97]:
R4 = R(0,90,0)
tmp = R1@R2@R3@R4
print(tmp)
print((deg(tmp)))
print("-"*20)
print(tmp@np.array([[1,0,0]]).T)
print("-"*20)
print(tmp@np.array([[0,1,0]]).T)
print("-"*20)
print(tmp@np.array([[0,0,1]]).T)
print("-"*20)

[[  6.12323400e-17   0.00000000e+00   1.00000000e+00]
 [  1.00000000e+00   2.14607521e-16  -6.12323400e-17]
 [ -2.07170437e-16   1.00000000e+00   1.26855306e-32]]
sin 2.0717043678169387e-16
1.5707963267948966 2.0717043678169387e-16 1.5707963267948966
(90.0, 1.1869991667472893e-14, 90.0)
--------------------
[[  6.12323400e-17]
 [  1.00000000e+00]
 [ -2.07170437e-16]]
--------------------
[[  0.00000000e+00]
 [  2.14607521e-16]
 [  1.00000000e+00]]
--------------------
[[  1.00000000e+00]
 [ -6.12323400e-17]
 [  1.26855306e-32]]
--------------------


In [98]:
R5 = R(30,0,0)
tmp = R1@R2@R3@R4@R5
print(tmp)
print((deg(tmp)))

[[  6.12323400e-17   5.00000000e-01   8.66025404e-01]
 [  1.00000000e+00   1.55239395e-16  -1.60332522e-16]
 [ -2.07170437e-16   8.66025404e-01  -5.00000000e-01]]
sin 2.0717043678169387e-16
2.0943951023931953 2.0717043678169387e-16 1.5707963267948966
(119.99999999999999, 1.1869991667472893e-14, 90.0)


In [99]:
R6 = R(30,0,0)
tmp = R1@R2@R3@R4@R5@R6
print(tmp)
print((deg(tmp)))

[[  6.12323400e-17   8.66025404e-01   5.00000000e-01]
 [  1.00000000e+00   5.42749985e-17  -2.16471735e-16]
 [ -2.07170437e-16   5.00000000e-01  -8.66025404e-01]]
sin 2.0717043678169387e-16
2.6179938779914944 2.0717043678169387e-16 1.5707963267948966
(150.0, 1.1869991667472893e-14, 90.0)


In [100]:
R7 = R(30,0,0)
tmp = R1@R2@R3@R4@R5@R6@R7
print(tmp)
print((deg(tmp)))
print("-"*20)
print(tmp@np.array([[1,0,0]]).T)
print("-"*20)
print(tmp@np.array([[0,1,0]]).T)
print("-"*20)
print(tmp@np.array([[0,0,1]]).T)
print("-"*20)

[[  6.12323400e-17   1.00000000e+00   2.07170437e-16]
 [  1.00000000e+00  -6.12323400e-17  -2.14607521e-16]
 [ -2.07170437e-16   2.14607521e-16  -1.00000000e+00]]
sin 2.0717043678169387e-16
3.141592653589793 2.0717043678169387e-16 1.5707963267948966
(180.0, 1.1869991667472893e-14, 90.0)
--------------------
[[  6.12323400e-17]
 [  1.00000000e+00]
 [ -2.07170437e-16]]
--------------------
[[  1.00000000e+00]
 [ -6.12323400e-17]
 [  2.14607521e-16]]
--------------------
[[  2.07170437e-16]
 [ -2.14607521e-16]
 [ -1.00000000e+00]]
--------------------


In [101]:
R8 = R(0,90,0)
tmp = R1@R2@R3@R4@R5@R6@R7@R8
print(tmp)
print((deg(tmp)))
print("-"*20)
print(tmp@np.array([[1,0,0]]).T)
print("-"*20)
print(tmp@np.array([[0,1,0]]).T)
print("-"*20)
print(tmp@np.array([[0,0,1]]).T)
print("-"*20)

[[ -2.07170437e-16   1.00000000e+00   6.12323400e-17]
 [  2.75839861e-16  -6.12323400e-17   1.00000000e+00]
 [  1.00000000e+00   2.14607521e-16  -2.68402777e-16]]
sin -0.8414709848078965
2.467112341804925 -1.5707963267948966 2.214971204632213
(141.35512477005918, -90.0, 126.90850176843364)
--------------------
[[ -2.07170437e-16]
 [  2.75839861e-16]
 [  1.00000000e+00]]
--------------------
[[  1.00000000e+00]
 [ -6.12323400e-17]
 [  2.14607521e-16]]
--------------------
[[  6.12323400e-17]
 [  1.00000000e+00]
 [ -2.68402777e-16]]
--------------------


In [102]:
R9 = R(0,0,180)
tmp = R1@R2@R3@R4@R5@R6@R7@R8@R9
print(tmp)
print((deg(tmp)))
print("-"*20)
print(tmp@np.array([[1,0,0]]).T)
print("-"*20)
print(tmp@np.array([[0,1,0]]).T)
print("-"*20)
print(tmp@np.array([[0,0,1]]).T)
print("-"*20)

[[  3.29635117e-16  -1.00000000e+00   6.12323400e-17]
 [ -2.75839861e-16   6.12323400e-17   1.00000000e+00]
 [ -1.00000000e+00  -3.37072201e-16  -2.68402777e-16]]
sin 0.8414709848078965
-2.2432629043980072 1.5707963267948966 -0.696782825307343
(-128.52949676026489, 90.0, -39.922715127312081)
--------------------
[[  3.29635117e-16]
 [ -2.75839861e-16]
 [ -1.00000000e+00]]
--------------------
[[ -1.00000000e+00]
 [  6.12323400e-17]
 [ -3.37072201e-16]]
--------------------
[[  6.12323400e-17]
 [  1.00000000e+00]
 [ -2.68402777e-16]]
--------------------
